In [1]:
import pandas as pd

paths = {
    "Academia de Ginastica": "Academia de Ginastica.xlsx",
    "Agencia Bancaria": "Agencia Bancaria.xlsx",
    "Escola Privada": "Escola Privada.xlsx",
    "Escola Pública": "Escola Pública.xlsx",
    "Faculdade" : "faculdade.xlsx",
    "Farmacia": "Farmacia.xlsx",
    "Fast Food": "Fast Food.xlsx",
    "Hipermercados e Supermercados": "Hipermercados e Supermercados.xlsx",
    "Hortifruti": "Hortifruti.xlsx",
    "Hospital": "Hospital.xlsx",
    "Petshop": "Petshop.xlsx",
    "Restaurante": "Restaurantes.xlsx",
    "Shopping Center": "Shopping Center.xlsx",

}

dfs = {k: pd.read_excel(v) for k, v in paths.items()}

# filter municipio to be São Paulo everywhere
dfs = {k: v[v["Município"] == "São Paulo"] for k, v in dfs.items()}

In [2]:

# drop Unnamed columns, Telecone, Municipio, Estado, Mesorregião	Região Geográfica	Microárea, Telefone
for k, v in dfs.items():
    v.drop(v.columns[v.columns.str.contains('unnamed', case=False)], axis=1, inplace=True, errors="ignore")
    v.drop(["Município", "Estado", "Mesorregião", "Microrregião", "Região Geográfica", "Microárea", "Telefone"], axis=1, inplace=True, errors="ignore")
    # make first column the id column and change it to id
    v.rename(columns={v.columns[0]: "id"}, inplace=True)
    v.set_index("id", inplace=True)

In [3]:
# iterate over all dataframes
for k, v in dfs.items():
    # if there is a column with "Nome da Rede", change it to "Rede"
    if "Nome da Rede" in v.columns:
        v.rename(columns={"Nome da Rede": "Rede"}, inplace=True)
    # if there is a column with the name in the list, change it to "Nome"
    list = ["Nome", "Nome da Unidade", "Nome Instituição"]
    for l in list:
        if l in v.columns:
            v.rename(columns={l: "Nome"}, inplace=True)

In [4]:
# display dfs heads
for k, v in dfs.items():
    display(k)
    display(v.head())
    display(v.shape)

'Academia de Ginastica'

,Rede,Nome,Localizado em,Endereço,Bairro,CEP
id,,,,,,
10.093.874,A! Body Tech,Brooklin Guararapes,Rua,"R Guararapes, 20",Alto Da Lapa,04561-000
10.156.197,Companhia Athletica,NaN,Shopping Center,"Av Roque Petroni Júnior, 1089",Chácara Santo Antônio,"[4707900, 4707970]"
10.395.293,Companhia Athletica,Cia111,Rua,"R José Guerra, 111",Chácara Santo Antônio,04719-030
11.093.385,Engenharia do Corpo,Academia Engenharia do Corpo,Rua,Av. Reg. Feijó,Vila Reg. Feijó,03342-001
11.093.386,Smart Fit,Academia Smart Fit Avenida Conselheiro Carrao,Rua,Av. Conselheiro Carrão,Vila Gomes Cardim,03403-000

(227, 6)

'Agencia Bancaria'

,Rede,Nome,Localizado em,Endereço,Bairro,CEP
id,,,,,,
10.024.712,Itaú,SP Teotonio Villela,Rua,"Av Senador Teotonio Vilela, 1192",Cidade Dutra,04801-000
10.024.726,Santander,001 - 4748 Interlagos II - SP - SP,Rua,"Av Nossa Senhora do Sabara, 2507",Vila Santana,04685-006
10.024.729,Santander,Guarapiranga,Rua,"Av de Pinedo, 353",Socorro,04764-001
10.024.730,Santander,Capela do Socorro/capital,Rua,"Av de Pinedo, 353",Socorro,04764-001
10.024.731,Bradesco,"Prime Capela do Socorro,urb. Sao Paulo, SP",Rua,"Av de Pinedo, 342",Socorro,04764-000

(1788, 6)

'Escola Privada'

,Código INEP,Rede,Nome,Localizado em,Endereço,Bairro,CEP,Alunos
id,,,,,,,,
10075255,35006951,Privada,Esc Part Miyagui Colegio,Rua,"Jericino, 550",Chacara California,3442000,75
10075262,35006962,Privada,Cr P Conv Anglicana Bernardo Giacomini Goncalves,Rua,"Jose Pedro de Carvalho Lima, 333",Jardim Parque Morumbi,5712080,214
10075268,35006970,Privada,Colegio Lua Ensino Fundamental,Rua,"Jose Piragibe, 36",Vila Indiana,5585040,60
10075269,35006971,Privada,Escola Crescente,Rua,"Clarindo, 5135",Vila Andrade,5718300,150
10075278,35006983,Privada,Colegio Essere,Rua,"Filomena Bocchi Pilli, 190",Jardim Monjolo,2961130,72

(4485, 8)

'Escola Pública'

,Código INEP,Rede,Nome,Localizado em,Endereço,Bairro,CEP,Alunos
id,,,,,,,,
10075295,35007002,Pública,Cemei Pacheco Gato,Rua,"Pacheco Gato, 2",Jardim Nove de Julho,3951060,294.0
10075296,35007003,Pública,Emei Cidade Tiradentes IV,Rua,"Eduardo Reuter, 410",Conjunto Habitacional Barro Branco II,8473533,346.0
10075297,35007004,Pública,Emei Lajeado II,Rua,"Joao da Silva Aguiar, 150",Lajeado,8452250,516.0
10075380,35007125,Pública,Ceu Cemei Vila Alpina,Rua,"Joao Pedro Lecor, 141",Jardim Avelino,3227190,364.0
10075381,35007126,Pública,Ceu Cemei Parque do Carmo,Rua,"Gaspar da Silva, 240",Jardim Nossa Senhora do Carmo,8275250,509.0

(2767, 8)

'Faculdade'

,Código do Local de Oferta,Código IES,Nome,Rede,Nome,Localizado em,Endereço,Bairro,CEP,Alunos
id,,,,,,,,,,
10.098.019,700217,17.608,Faculdade de Educação Paulistana,Privada,Unidade Sede,Rua,"R Tito, 1175",Vila Ipojuca,"[4877190, 2323180, 2162100, 5205130, 5271100, ...","92,00000"
10.098.020,657912,461.000,Faculdade Armando Alvares Penteado,Privada,Unidade Sede,Rua,"Rua Alagoas, 903",Pacaembu,[1242902],"2.901,00000"
10.098.021,1069907,12.723,Faculdade de Tecnologia Finaci,Privada,Unidade Brigadeiro,Rua,"Av Brigadeiro Luís Antônio, 2867",Paraíso,"[1317000, 1317001, 1317002, 1317901, 1317902, ...","8,00000"
10.098.022,2788,221.000,Universidade Cruzeiro do Sul,Privada,Polo Sp_liberdade,Rua,"R Galvão Bueno, 868",Liberdade/São Joaquim,"[1506000, 1506900]","4.596,00000"
10.098.023,657790,221.000,Universidade Cruzeiro do Sul,Privada,Polo Sp_sao Miguel Paulista (sede),Rua,"Av Doutor Ussiel Cirilo, 225",Vila Jacuí,[8060070],"15.511,00000"

(298, 10)

'Farmacia'

,Rede,Nome,Localizado em,Endereço,Bairro,CEP
id,,,,,,
10.100.701,Drogarias Ultra Popular,Drogalella LTDA - Epp,Rua,"AL Barros, 19",Santa Cecilia,01232-000
10.100.702,Drogarias Ultra Popular,Drogalene LTDA,Rua,"Av Sao Luis, 51",Republica,01046-001
10.100.708,Drogarias Ultra Popular,Drogaria Empresarial LTDA - Matriz,Rua,"R Joao Fernandes Camisa Nova Junior, 476",Jd São Luiz,05844-000
10.100.710,Drogarias Ultra Popular,Drogaria Lambert Rosa LTDA - Epp,Rua,"R Paulo de Faria, 23",Tucuruvi,02267-000
10.100.711,Drogarias Ultra Popular,Drogaria Largo do Paissandu LTDA - ME,Rua,"Largo do Paissandu, 40",Centro,01034-010

(1173, 6)

'Fast Food'

,Nome,Rede,Localizado em,Endereço,Bairro,CEP
id,,,,,,
10314145,Madero Burger Aeroporto de Congonhas,Madero Express,Rua,"Av Washington Luís, S/N",Vila Congonhas,04626-911
10396576,Madero Burger Quatá,Madero Express,Rua,"R Quatá, 662",Vila Olímpia,04546-044
10396577,Madero Burger Vila Mariana,Madero Express,Rua,"Av Conselheiro Rodrigues Alves, 379",Vila Mariana,04014-011
10983161,Subway,Subway,Rua,Av. Sílvio Ribeiro Aragão,Av. Sílvio Ribeiro Aragão,05776-510
10983174,Mcdonalds,Mcdonald´s,Rua,R. Domingos de Morais,Vila Mariana,04036-000

(953, 6)

'Hipermercados e Supermercados'

,Rede,Localizado em,Nome,Endereço,Bairro,CEP
id,,,,,,
10.029.385,Extra Supermercado,Rua,Santana,"R Conselheiro Moreira De Barros, 2075",Mandaqui,2430000
10.029.386,Extra Supermercado,Rua,Rego Freitas,"R Rego Freitas, 172",República,1220000
10.029.388,Extra Supermercado,Rua,Jardim Angela,"Estr Do M. Boi Mirim, 4374",M`Boi Mirim,4948030
10.029.389,Extra Supermercado,Rua,Glicério,"R Glicerio, 90",Praça João Mendes,1514000
10.029.390,Extra Supermercado,Rua,Vila Nova Cachoeirinha,"Av Inajar De Souza, 5550",Jardim Peri,2861190

(1084, 6)

'Hortifruti'

,Rede,Localizado em,Nome,Endereço,Bairro,CEP
id,,,,,,
10.071.506,Natural da Terra,Rua,Natural da Terra - Tatuapé,Rua Apucarana,Tatuapé,03311-001
10.092.987,Oba Hortifruti,Shopping Center,Shopping Market Place,Rua Chucri Curi,Vila Cordeiro,35701-248
10.092.988,Oba Hortifruti,Rua,Vila Mascote,Rua Água Santa,Vila Mascote,37044-270
10.140.810,Natural da Terra,Rua,Natural da Terra - Moema,Alameda dos Arapanés,Moema,04524-001
10.140.811,Natural da Terra,Rua,Natural da Terra - Nhambiquaras,Alameda dos Nhambiquaras,Indianópolis,04085-000

(44, 6)

'Hospital'

,Nome,Endereço,Localizado em,Bairro,CEP,N° de Leitos,Esfera Administrativa,Esfera Administrativa Tipo
id,,,,,,,,
10.034.921,Hosp Mun Josanias Castanha Braga,"R Euzebio Coghi, 841",Rua,Jardim Roschel,04883-290,314.0,Pública,Municipal
10.034.930,Hospital Municipal Guarapiranga,"Estr Da Riviera, 4742",Rua,Riviera Paulista,04916-000,259.0,Pública,Municipal
10.034.931,Upa Pedreira Dr Cesar Antunes Da Rocha,"Av Nossa Senhora Do Sabara, 4901",Rua,Vila Emir,04447-021,0.0,Pública,Municipal
10.034.942,Clinica Infantil Santa Isabella,"R Verbo Divino, 246",Rua,Granja Julieta,04719-000,3.0,Privada,Privada
10.034.947,Hospital Sancta Maggiore,"R Francisco Tramontano, 100",Rua,Real Parque,05686-902,213.0,Privada,Privada

(384, 8)

'Petshop'

,Rede,Nome,Localizado em,Endereço,Bairro,CEP
id,,,,,,
10.080.177,Petland,Pinheiros,Rua,"Av Henrique Schaumann, 679 Lj 2",Pinheiros,05413-021
10.092.771,Petz,Petz Cerro Corá,Rua,"R Cerro Corá, 1950",Vila Romana,05061-300
10.092.772,Petz,Petz Lauzane Paulista,Rua,"Av Direitos Humanos, 1436",Lauzane Paulista,02475-001
10.092.773,Petz,Petz Nações Unidas,Rua,"Av das Nações Unidas, 20727",Vila Almeida,04795-100
10.092.774,Petz,Petz Vila Mariana,Rua,"R Vergueiro, 2604",Vila Mariana,04102-000

(129, 6)

'Restaurante'

,Rede,Nome,Localizado em,Endereço,Bairro,CEP
id,,,,,,
10.057.854,Madero,Madero Steak House Brascan,Rua,"R Joaquim Floriano, 466",Itaim Bibi,04534-002
10.108.028,Madero,Madero Steak House SP Market,Shopping Center,"Av Das Nações, 22540",Vila Almeida,04696-005
10.203.344,Madero,Pátio Paulista,Shopping Center,R Treze de Maio 1947,Bela Vista,01327-900
10.253.147,Madero,Madero Steak House  Shopping Jardim Sul,Shopping Center,R Itacaiúna 61,Vila Andrade,05716-070
10.396.572,Madero,Madero Steak House Açoce,Rua,"Av Açocê, 249",Indianápolis,04075-021

(250, 6)

'Shopping Center'

,Nome,Localizado em,Endereço,Bairro,CEP,Adm / Incorp,Categoria,Status,Estágio da Obra,Porte,ABL(M²),Vagas,Total de Lojas,Lojas Ancora,Total de Lojas Ancora,Total de Pisos
id,,,,,,,,,,,,,,,,
10128725,Shopping Trimais,Rua,Av Tucuruvi 220,Tucuruvi,NaN,Ad Shopping,Tradicional,Inaugurado,Ativo,Não Definido,25500.0,2000.0,150.0,NaN,3.0,15.0
10395925,Andorinha Hiper Center,Rua,"Av. Parada Pinto, 2262",Lauzane Paulista,NaN,Ad Shopping,Não Definido,Inaugurado,Ativo,Não Definido,13000.0,1270.0,75.0,NaN,2.0,NaN
1290654,Top Center Shopping,Rua,Av Paulista 854,Bela Vista,01311-000,Gazit Brasil Ltda,Tradicional,Inaugurado,Ativo,Vizinhança,6557.0,361.0,85.0,NaN,7.0,4.0
2884597,Jaragua Cenesp,Rua,Av Maria Coelho Aguiar 215,Jd São Luís,05804-900,Sol Panamby,Tradicional,Inaugurado,Ativo,Pequeno,11612.0,4400.0,107.0,NaN,NaN,1.0
357943,Santana Shopping,Rua,Av Voluntários da Pátria 2182,Santana,02010-820,Administração Particular,Tradicional,Inaugurado,Ativo,Vizinhança,5000.0,100.0,25.0,NaN,NaN,NaN

(59, 16)

In [5]:
# add the first and last 5 letters of the name to the id
for k, v in dfs.items():
    v.index = v.index.map(lambda x: f"{k}_{x}")

In [6]:
# create a Tipo column with the key
for k, v in dfs.items():
    v["Tipo"] = k

In [7]:
dfs["Academia de Ginastica"].head()

,Rede,Nome,Localizado em,Endereço,Bairro,CEP,Tipo
id,,,,,,,
Academia de Ginastica_10.093.874,A! Body Tech,Brooklin Guararapes,Rua,"R Guararapes, 20",Alto Da Lapa,04561-000,Academia de Ginastica
Academia de Ginastica_10.156.197,Companhia Athletica,NaN,Shopping Center,"Av Roque Petroni Júnior, 1089",Chácara Santo Antônio,"[4707900, 4707970]",Academia de Ginastica
Academia de Ginastica_10.395.293,Companhia Athletica,Cia111,Rua,"R José Guerra, 111",Chácara Santo Antônio,04719-030,Academia de Ginastica
Academia de Ginastica_11.093.385,Engenharia do Corpo,Academia Engenharia do Corpo,Rua,Av. Reg. Feijó,Vila Reg. Feijó,03342-001,Academia de Ginastica
Academia de Ginastica_11.093.386,Smart Fit,Academia Smart Fit Avenida Conselheiro Carrao,Rua,Av. Conselheiro Carrão,Vila Gomes Cardim,03403-000,Academia de Ginastica

In [8]:
# keep only Rede	Nome	Localizado em	Endereço	Bairro	CEP	Tipo
for k, v in dfs.items():
    v.drop([c for c in v.columns if c not in ["Rede", "Nome", "Localizado em", "Endereço", "Bairro", "CEP", "Tipo"]], axis=1, inplace=True)
    # if there is no Rede column, create it null
    if "Rede" not in v.columns:
        v["Rede"] = None

In [9]:
# print all cols to check
for k, v in dfs.items():
    # sort ['Rede', 'Nome', 'Localizado em', 'Endereço', 'Bairro', 'CEP', 'Tipo']
    v = v[['Rede', 'Nome', 'Localizado em', 'Endereço', 'Bairro', 'CEP', 'Tipo']]
    dfs[k] = v

In [10]:
# print heads
for k, v in dfs.items():
    display(k)
    display(v.head())
    display(v.shape)

'Academia de Ginastica'

,Rede,Nome,Localizado em,Endereço,Bairro,CEP,Tipo
id,,,,,,,
Academia de Ginastica_10.093.874,A! Body Tech,Brooklin Guararapes,Rua,"R Guararapes, 20",Alto Da Lapa,04561-000,Academia de Ginastica
Academia de Ginastica_10.156.197,Companhia Athletica,NaN,Shopping Center,"Av Roque Petroni Júnior, 1089",Chácara Santo Antônio,"[4707900, 4707970]",Academia de Ginastica
Academia de Ginastica_10.395.293,Companhia Athletica,Cia111,Rua,"R José Guerra, 111",Chácara Santo Antônio,04719-030,Academia de Ginastica
Academia de Ginastica_11.093.385,Engenharia do Corpo,Academia Engenharia do Corpo,Rua,Av. Reg. Feijó,Vila Reg. Feijó,03342-001,Academia de Ginastica
Academia de Ginastica_11.093.386,Smart Fit,Academia Smart Fit Avenida Conselheiro Carrao,Rua,Av. Conselheiro Carrão,Vila Gomes Cardim,03403-000,Academia de Ginastica

(227, 7)

'Agencia Bancaria'

,Rede,Nome,Localizado em,Endereço,Bairro,CEP,Tipo
id,,,,,,,
Agencia Bancaria_10.024.712,Itaú,SP Teotonio Villela,Rua,"Av Senador Teotonio Vilela, 1192",Cidade Dutra,04801-000,Agencia Bancaria
Agencia Bancaria_10.024.726,Santander,001 - 4748 Interlagos II - SP - SP,Rua,"Av Nossa Senhora do Sabara, 2507",Vila Santana,04685-006,Agencia Bancaria
Agencia Bancaria_10.024.729,Santander,Guarapiranga,Rua,"Av de Pinedo, 353",Socorro,04764-001,Agencia Bancaria
Agencia Bancaria_10.024.730,Santander,Capela do Socorro/capital,Rua,"Av de Pinedo, 353",Socorro,04764-001,Agencia Bancaria
Agencia Bancaria_10.024.731,Bradesco,"Prime Capela do Socorro,urb. Sao Paulo, SP",Rua,"Av de Pinedo, 342",Socorro,04764-000,Agencia Bancaria

(1788, 7)

'Escola Privada'

,Rede,Nome,Localizado em,Endereço,Bairro,CEP,Tipo
id,,,,,,,
Escola Privada_10075255,Privada,Esc Part Miyagui Colegio,Rua,"Jericino, 550",Chacara California,3442000,Escola Privada
Escola Privada_10075262,Privada,Cr P Conv Anglicana Bernardo Giacomini Goncalves,Rua,"Jose Pedro de Carvalho Lima, 333",Jardim Parque Morumbi,5712080,Escola Privada
Escola Privada_10075268,Privada,Colegio Lua Ensino Fundamental,Rua,"Jose Piragibe, 36",Vila Indiana,5585040,Escola Privada
Escola Privada_10075269,Privada,Escola Crescente,Rua,"Clarindo, 5135",Vila Andrade,5718300,Escola Privada
Escola Privada_10075278,Privada,Colegio Essere,Rua,"Filomena Bocchi Pilli, 190",Jardim Monjolo,2961130,Escola Privada

(4485, 7)

'Escola Pública'

,Rede,Nome,Localizado em,Endereço,Bairro,CEP,Tipo
id,,,,,,,
Escola Pública_10075295,Pública,Cemei Pacheco Gato,Rua,"Pacheco Gato, 2",Jardim Nove de Julho,3951060,Escola Pública
Escola Pública_10075296,Pública,Emei Cidade Tiradentes IV,Rua,"Eduardo Reuter, 410",Conjunto Habitacional Barro Branco II,8473533,Escola Pública
Escola Pública_10075297,Pública,Emei Lajeado II,Rua,"Joao da Silva Aguiar, 150",Lajeado,8452250,Escola Pública
Escola Pública_10075380,Pública,Ceu Cemei Vila Alpina,Rua,"Joao Pedro Lecor, 141",Jardim Avelino,3227190,Escola Pública
Escola Pública_10075381,Pública,Ceu Cemei Parque do Carmo,Rua,"Gaspar da Silva, 240",Jardim Nossa Senhora do Carmo,8275250,Escola Pública

(2767, 7)

'Faculdade'

,Rede,Nome,Nome,Localizado em,Endereço,Bairro,CEP,Tipo
id,,,,,,,,
Faculdade_10.098.019,Privada,Faculdade de Educação Paulistana,Unidade Sede,Rua,"R Tito, 1175",Vila Ipojuca,"[4877190, 2323180, 2162100, 5205130, 5271100, ...",Faculdade
Faculdade_10.098.020,Privada,Faculdade Armando Alvares Penteado,Unidade Sede,Rua,"Rua Alagoas, 903",Pacaembu,[1242902],Faculdade
Faculdade_10.098.021,Privada,Faculdade de Tecnologia Finaci,Unidade Brigadeiro,Rua,"Av Brigadeiro Luís Antônio, 2867",Paraíso,"[1317000, 1317001, 1317002, 1317901, 1317902, ...",Faculdade
Faculdade_10.098.022,Privada,Universidade Cruzeiro do Sul,Polo Sp_liberdade,Rua,"R Galvão Bueno, 868",Liberdade/São Joaquim,"[1506000, 1506900]",Faculdade
Faculdade_10.098.023,Privada,Universidade Cruzeiro do Sul,Polo Sp_sao Miguel Paulista (sede),Rua,"Av Doutor Ussiel Cirilo, 225",Vila Jacuí,[8060070],Faculdade

(298, 8)

'Farmacia'

,Rede,Nome,Localizado em,Endereço,Bairro,CEP,Tipo
id,,,,,,,
Farmacia_10.100.701,Drogarias Ultra Popular,Drogalella LTDA - Epp,Rua,"AL Barros, 19",Santa Cecilia,01232-000,Farmacia
Farmacia_10.100.702,Drogarias Ultra Popular,Drogalene LTDA,Rua,"Av Sao Luis, 51",Republica,01046-001,Farmacia
Farmacia_10.100.708,Drogarias Ultra Popular,Drogaria Empresarial LTDA - Matriz,Rua,"R Joao Fernandes Camisa Nova Junior, 476",Jd São Luiz,05844-000,Farmacia
Farmacia_10.100.710,Drogarias Ultra Popular,Drogaria Lambert Rosa LTDA - Epp,Rua,"R Paulo de Faria, 23",Tucuruvi,02267-000,Farmacia
Farmacia_10.100.711,Drogarias Ultra Popular,Drogaria Largo do Paissandu LTDA - ME,Rua,"Largo do Paissandu, 40",Centro,01034-010,Farmacia

(1173, 7)

'Fast Food'

,Rede,Nome,Localizado em,Endereço,Bairro,CEP,Tipo
id,,,,,,,
Fast Food_10314145,Madero Express,Madero Burger Aeroporto de Congonhas,Rua,"Av Washington Luís, S/N",Vila Congonhas,04626-911,Fast Food
Fast Food_10396576,Madero Express,Madero Burger Quatá,Rua,"R Quatá, 662",Vila Olímpia,04546-044,Fast Food
Fast Food_10396577,Madero Express,Madero Burger Vila Mariana,Rua,"Av Conselheiro Rodrigues Alves, 379",Vila Mariana,04014-011,Fast Food
Fast Food_10983161,Subway,Subway,Rua,Av. Sílvio Ribeiro Aragão,Av. Sílvio Ribeiro Aragão,05776-510,Fast Food
Fast Food_10983174,Mcdonald´s,Mcdonalds,Rua,R. Domingos de Morais,Vila Mariana,04036-000,Fast Food

(953, 7)

'Hipermercados e Supermercados'

,Rede,Nome,Localizado em,Endereço,Bairro,CEP,Tipo
id,,,,,,,
Hipermercados e Supermercados_10.029.385,Extra Supermercado,Santana,Rua,"R Conselheiro Moreira De Barros, 2075",Mandaqui,2430000,Hipermercados e Supermercados
Hipermercados e Supermercados_10.029.386,Extra Supermercado,Rego Freitas,Rua,"R Rego Freitas, 172",República,1220000,Hipermercados e Supermercados
Hipermercados e Supermercados_10.029.388,Extra Supermercado,Jardim Angela,Rua,"Estr Do M. Boi Mirim, 4374",M`Boi Mirim,4948030,Hipermercados e Supermercados
Hipermercados e Supermercados_10.029.389,Extra Supermercado,Glicério,Rua,"R Glicerio, 90",Praça João Mendes,1514000,Hipermercados e Supermercados
Hipermercados e Supermercados_10.029.390,Extra Supermercado,Vila Nova Cachoeirinha,Rua,"Av Inajar De Souza, 5550",Jardim Peri,2861190,Hipermercados e Supermercados

(1084, 7)

'Hortifruti'

,Rede,Nome,Localizado em,Endereço,Bairro,CEP,Tipo
id,,,,,,,
Hortifruti_10.071.506,Natural da Terra,Natural da Terra - Tatuapé,Rua,Rua Apucarana,Tatuapé,03311-001,Hortifruti
Hortifruti_10.092.987,Oba Hortifruti,Shopping Market Place,Shopping Center,Rua Chucri Curi,Vila Cordeiro,35701-248,Hortifruti
Hortifruti_10.092.988,Oba Hortifruti,Vila Mascote,Rua,Rua Água Santa,Vila Mascote,37044-270,Hortifruti
Hortifruti_10.140.810,Natural da Terra,Natural da Terra - Moema,Rua,Alameda dos Arapanés,Moema,04524-001,Hortifruti
Hortifruti_10.140.811,Natural da Terra,Natural da Terra - Nhambiquaras,Rua,Alameda dos Nhambiquaras,Indianópolis,04085-000,Hortifruti

(44, 7)

'Hospital'

,Rede,Nome,Localizado em,Endereço,Bairro,CEP,Tipo
id,,,,,,,
Hospital_10.034.921,None,Hosp Mun Josanias Castanha Braga,Rua,"R Euzebio Coghi, 841",Jardim Roschel,04883-290,Hospital
Hospital_10.034.930,None,Hospital Municipal Guarapiranga,Rua,"Estr Da Riviera, 4742",Riviera Paulista,04916-000,Hospital
Hospital_10.034.931,None,Upa Pedreira Dr Cesar Antunes Da Rocha,Rua,"Av Nossa Senhora Do Sabara, 4901",Vila Emir,04447-021,Hospital
Hospital_10.034.942,None,Clinica Infantil Santa Isabella,Rua,"R Verbo Divino, 246",Granja Julieta,04719-000,Hospital
Hospital_10.034.947,None,Hospital Sancta Maggiore,Rua,"R Francisco Tramontano, 100",Real Parque,05686-902,Hospital

(384, 7)

'Petshop'

,Rede,Nome,Localizado em,Endereço,Bairro,CEP,Tipo
id,,,,,,,
Petshop_10.080.177,Petland,Pinheiros,Rua,"Av Henrique Schaumann, 679 Lj 2",Pinheiros,05413-021,Petshop
Petshop_10.092.771,Petz,Petz Cerro Corá,Rua,"R Cerro Corá, 1950",Vila Romana,05061-300,Petshop
Petshop_10.092.772,Petz,Petz Lauzane Paulista,Rua,"Av Direitos Humanos, 1436",Lauzane Paulista,02475-001,Petshop
Petshop_10.092.773,Petz,Petz Nações Unidas,Rua,"Av das Nações Unidas, 20727",Vila Almeida,04795-100,Petshop
Petshop_10.092.774,Petz,Petz Vila Mariana,Rua,"R Vergueiro, 2604",Vila Mariana,04102-000,Petshop

(129, 7)

'Restaurante'

,Rede,Nome,Localizado em,Endereço,Bairro,CEP,Tipo
id,,,,,,,
Restaurante_10.057.854,Madero,Madero Steak House Brascan,Rua,"R Joaquim Floriano, 466",Itaim Bibi,04534-002,Restaurante
Restaurante_10.108.028,Madero,Madero Steak House SP Market,Shopping Center,"Av Das Nações, 22540",Vila Almeida,04696-005,Restaurante
Restaurante_10.203.344,Madero,Pátio Paulista,Shopping Center,R Treze de Maio 1947,Bela Vista,01327-900,Restaurante
Restaurante_10.253.147,Madero,Madero Steak House  Shopping Jardim Sul,Shopping Center,R Itacaiúna 61,Vila Andrade,05716-070,Restaurante
Restaurante_10.396.572,Madero,Madero Steak House Açoce,Rua,"Av Açocê, 249",Indianápolis,04075-021,Restaurante

(250, 7)

'Shopping Center'

,Rede,Nome,Localizado em,Endereço,Bairro,CEP,Tipo
id,,,,,,,
Shopping Center_10128725,None,Shopping Trimais,Rua,Av Tucuruvi 220,Tucuruvi,NaN,Shopping Center
Shopping Center_10395925,None,Andorinha Hiper Center,Rua,"Av. Parada Pinto, 2262",Lauzane Paulista,NaN,Shopping Center
Shopping Center_1290654,None,Top Center Shopping,Rua,Av Paulista 854,Bela Vista,01311-000,Shopping Center
Shopping Center_2884597,None,Jaragua Cenesp,Rua,Av Maria Coelho Aguiar 215,Jd São Luís,05804-900,Shopping Center
Shopping Center_357943,None,Santana Shopping,Rua,Av Voluntários da Pátria 2182,Santana,02010-820,Shopping Center

(59, 7)

In [11]:
# save all dataframes to an Excel
with pd.ExcelWriter("PontosInteresse.xlsx") as writer:
    for k, v in dfs.items():
        v.to_excel(writer, sheet_name=k)

In [12]:
# read the excel and join all sheets into the same dataframe
df_full = pd.read_excel("PontosInteresse.xlsx", sheet_name=None)
df_full = pd.concat(df_full.values())

In [13]:
dfs["Shopping Center"].head()

,Rede,Nome,Localizado em,Endereço,Bairro,CEP,Tipo
id,,,,,,,
Shopping Center_10128725,None,Shopping Trimais,Rua,Av Tucuruvi 220,Tucuruvi,NaN,Shopping Center
Shopping Center_10395925,None,Andorinha Hiper Center,Rua,"Av. Parada Pinto, 2262",Lauzane Paulista,NaN,Shopping Center
Shopping Center_1290654,None,Top Center Shopping,Rua,Av Paulista 854,Bela Vista,01311-000,Shopping Center
Shopping Center_2884597,None,Jaragua Cenesp,Rua,Av Maria Coelho Aguiar 215,Jd São Luís,05804-900,Shopping Center
Shopping Center_357943,None,Santana Shopping,Rua,Av Voluntários da Pátria 2182,Santana,02010-820,Shopping Center

In [ ]:
import requests

# mapbox token
token = "pk.eyJ1IjoicHJvamV0b2RhZG9zIiwiYSI6ImNtMXdiNjVobTBpa2Eya3BsMnR5OWxsd3AifQ.SGh5qTES1kmMN3VNFzZAwQ"

# mapbox url
"https://api.mapbox.com/search/geocode/v6/forward?q="

# search_text is df["Endereço"] + df["Bairro"]

df = dfs["Escola Pública"]

# get the latitude and longitude from the search_text
# add the latitude and longitude to the dataframe
count = 0
for i, row in df.iterrows():
    search_text = f"{row['Endereço']} {row['Bairro']} São Paulo"
    # proximity to São Paulo
    # proximity	string	Bias the response to favor results that are closer to this location. Provided as two comma-separated coordinates in longitude,latitude order, or the string ip to bias based on reverse IP lookup.
    SAO_PAULO = (-46.63389, -23.55028)
    url = f"https://api.mapbox.com/search/geocode/v6/forward?q={search_text}&access_token={token}&proximity={SAO_PAULO[0]},{SAO_PAULO[1]}"
    response = requests.get(url)
    data = response.json()

    if not data['features']:
        continue
    
    df.at[i, "Latitude"] = data['features'][0]["geometry"]["coordinates"][1]
    df.at[i, "Longitude"] = data['features'][0]["geometry"]["coordinates"][0]

    # save to csv
    count += 1
    if count % 100 == 0:
        print(count)

    # at every 1000 rows, save to csv
    if count % 1000 == 0:
        df.to_csv("Escola Publica.csv")

100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700

In [17]:
df

,Rede,Nome,Localizado em,Endereço,Bairro,CEP,Tipo,Latitude,Longitude
id,,,,,,,,,
Escola Privada_10075255,Privada,Esc Part Miyagui Colegio,Rua,"Jericino, 550",Chacara California,3442000,Escola Privada,-23.496655,-46.890235
Escola Privada_10075262,Privada,Cr P Conv Anglicana Bernardo Giacomini Goncalves,Rua,"Jose Pedro de Carvalho Lima, 333",Jardim Parque Morumbi,5712080,Escola Privada,-23.621929,-46.729650
Escola Privada_10075268,Privada,Colegio Lua Ensino Fundamental,Rua,"Jose Piragibe, 36",Vila Indiana,5585040,Escola Privada,-23.779579,-45.358564
Escola Privada_10075269,Privada,Escola Crescente,Rua,"Clarindo, 5135",Vila Andrade,5718300,Escola Privada,-23.635030,-46.736187
Escola Privada_10075278,Privada,Colegio Essere,Rua,"Filomena Bocchi Pilli, 190",Jardim Monjolo,2961130,Escola Privada,-23.493654,-46.698988
...,...,...,...,...,...,...,...,...,...
Escola Privada_8084337,Privada,Escola Luminova,Rua,"Ibitirama, 447",Vila Prudente,3134001,Escola Privada,-23.585706,-46.583893
Escola Privada_8084353,Privada,Escola Luminova Unidade Bom Retiro,Rua,"Prates, 782 e 790",Bom Retiro,1121000,Escola Privada,-23.527334,-46.634779
Escola Privada_8084392,Privada,Escola Luminova Unidade Barra Funda,Rua,"Prof Walter Lerner, 129",Barra Funda,1139020,Escola Privada,-23.519570,-46.674173
Escola Privada_8084393,Privada,Proz,Rua,"Ken Sugaya, 395",Itaquera,8210100,Escola Privada,-23.540383,-46.453029
Escola Privada_8084403,Privada,Avenues Sao Paulo,Rua,"Pedro Avancine, 73",Jardim Panorama,5679160,Escola Privada,-23.652387,-46.533937

In [18]:
df.to_csv("escola_privada.csv")

## Tratar estabelecimentos restantes

## Academia de Ginastica

In [11]:
import pandas as pd
import requests

# Carrega o arquivo Excel
df_full = pd.read_excel("PontosInteresse.xlsx", sheet_name=None)
name = "Academia de Ginastica"
df = df_full[name]

# Adiciona colunas para Latitude e Longitude, se não existirem
if "Latitude" not in df.columns:
    df["Latitude"] = None
if "Longitude" not in df.columns:
    df["Longitude"] = None

# Token e endpoint do Mapbox
token = "pk.eyJ1IjoicHJvamV0b2RhZG9zIiwiYSI6ImNtMXdiNjVobTBpa2Eya3BsMnR5OWxsd3AifQ.SGh5qTES1kmMN3VNFzZAwQ"
SAO_PAULO = (-46.63389, -23.55028)

# Loop para obter coordenadas de cada endereço
count = 0
for i, row in df.iterrows():
    search_text = f"{row['Endereço']} {row['Bairro']} São Paulo"
    url = f"https://api.mapbox.com/geocoding/v5/mapbox.places/{search_text}.json?access_token={token}&proximity={SAO_PAULO[0]},{SAO_PAULO[1]}"

    try:
        response = requests.get(url)
        data = response.json()

        # Verifica se há dados nas features
        if not data.get("features"):
            continue

        # Atualiza DataFrame com Latitude e Longitude
        df.at[i, "Latitude"] = data["features"][0]["geometry"]["coordinates"][1]
        df.at[i, "Longitude"] = data["features"][0]["geometry"]["coordinates"][0]

        # Salva o progresso
        count += 1
        if count % 100 == 0:
            print(f"{count} registros processados")

        # A cada 1000 linhas, salva o CSV
        if count % 1000 == 0:
            df.to_csv(f"{name}.csv", index=False)

    except requests.exceptions.RequestException as e:
        print(f"Erro na solicitação para o endereço {search_text}: {e}")

# Salva o arquivo final
df.to_csv(f"{name}.csv", index=False)

100 registros processados
200 registros processados

## Agencia Bancaria

In [12]:
import pandas as pd
import requests

# Carrega o arquivo Excel
df_full = pd.read_excel("PontosInteresse.xlsx", sheet_name=None)
name = "Agencia Bancaria"
df = df_full[name]

# Adiciona colunas para Latitude e Longitude, se não existirem
if "Latitude" not in df.columns:
    df["Latitude"] = None
if "Longitude" not in df.columns:
    df["Longitude"] = None

# Token e endpoint do Mapbox
token = "pk.eyJ1IjoicHJvamV0b2RhZG9zIiwiYSI6ImNtMXdiNjVobTBpa2Eya3BsMnR5OWxsd3AifQ.SGh5qTES1kmMN3VNFzZAwQ"
SAO_PAULO = (-46.63389, -23.55028)

# Loop para obter coordenadas de cada endereço
count = 0
for i, row in df.iterrows():
    search_text = f"{row['Endereço']} {row['Bairro']} São Paulo"
    url = f"https://api.mapbox.com/geocoding/v5/mapbox.places/{search_text}.json?access_token={token}&proximity={SAO_PAULO[0]},{SAO_PAULO[1]}"

    try:
        response = requests.get(url)
        data = response.json()

        # Verifica se há dados nas features
        if not data.get("features"):
            continue

        # Atualiza DataFrame com Latitude e Longitude
        df.at[i, "Latitude"] = data["features"][0]["geometry"]["coordinates"][1]
        df.at[i, "Longitude"] = data["features"][0]["geometry"]["coordinates"][0]

        # Salva o progresso
        count += 1
        if count % 100 == 0:
            print(f"{count} registros processados")

        # A cada 1000 linhas, salva o CSV
        if count % 1000 == 0:
            df.to_csv(f"{name}.csv", index=False)

    except requests.exceptions.RequestException as e:
        print(f"Erro na solicitação para o endereço {search_text}: {e}")

# Salva o arquivo final
df.to_csv(f"{name}.csv", index=False)

100 registros processados
200 registros processados
300 registros processados
400 registros processados
500 registros processados
600 registros processados
700 registros processados
800 registros processados
900 registros processados
1000 registros processados
1100 registros processados
1200 registros processados
1300 registros processados
1400 registros processados
1500 registros processados
1600 registros processados
1700 registros processados

## Faculdade

In [13]:
import pandas as pd
import requests

# Carrega o arquivo Excel
df_full = pd.read_excel("PontosInteresse.xlsx", sheet_name=None)
name = "Faculdade"
df = df_full[name]

# Adiciona colunas para Latitude e Longitude, se não existirem
if "Latitude" not in df.columns:
    df["Latitude"] = None
if "Longitude" not in df.columns:
    df["Longitude"] = None

# Token e endpoint do Mapbox
token = "pk.eyJ1IjoicHJvamV0b2RhZG9zIiwiYSI6ImNtMXdiNjVobTBpa2Eya3BsMnR5OWxsd3AifQ.SGh5qTES1kmMN3VNFzZAwQ"
SAO_PAULO = (-46.63389, -23.55028)

# Loop para obter coordenadas de cada endereço
count = 0
for i, row in df.iterrows():
    search_text = f"{row['Endereço']} {row['Bairro']} São Paulo"
    url = f"https://api.mapbox.com/geocoding/v5/mapbox.places/{search_text}.json?access_token={token}&proximity={SAO_PAULO[0]},{SAO_PAULO[1]}"

    try:
        response = requests.get(url)
        data = response.json()

        # Verifica se há dados nas features
        if not data.get("features"):
            continue

        # Atualiza DataFrame com Latitude e Longitude
        df.at[i, "Latitude"] = data["features"][0]["geometry"]["coordinates"][1]
        df.at[i, "Longitude"] = data["features"][0]["geometry"]["coordinates"][0]

        # Salva o progresso
        count += 1
        if count % 100 == 0:
            print(f"{count} registros processados")

        # A cada 1000 linhas, salva o CSV
        if count % 1000 == 0:
            df.to_csv(f"{name}.csv", index=False)

    except requests.exceptions.RequestException as e:
        print(f"Erro na solicitação para o endereço {search_text}: {e}")

# Salva o arquivo final
df.to_csv(f"{name}.csv", index=False)

100 registros processados
200 registros processados

## Farmacia

In [15]:
import pandas as pd
import requests

# Carrega o arquivo Excel
df_full = pd.read_excel("PontosInteresse.xlsx", sheet_name=None)
name = "Farmacia"
df = df_full[name]

# Adiciona colunas para Latitude e Longitude, se não existirem
if "Latitude" not in df.columns:
    df["Latitude"] = None
if "Longitude" not in df.columns:
    df["Longitude"] = None

# Token e endpoint do Mapbox
token = "pk.eyJ1IjoicHJvamV0b2RhZG9zIiwiYSI6ImNtMXdiNjVobTBpa2Eya3BsMnR5OWxsd3AifQ.SGh5qTES1kmMN3VNFzZAwQ"
SAO_PAULO = (-46.63389, -23.55028)

# Loop para obter coordenadas de cada endereço
count = 0
for i, row in df.iterrows():
    search_text = f"{row['Endereço']} {row['Bairro']} São Paulo"
    url = f"https://api.mapbox.com/geocoding/v5/mapbox.places/{search_text}.json?access_token={token}&proximity={SAO_PAULO[0]},{SAO_PAULO[1]}"

    try:
        response = requests.get(url)
        data = response.json()

        # Verifica se há dados nas features
        if not data.get("features"):
            continue

        # Atualiza DataFrame com Latitude e Longitude
        df.at[i, "Latitude"] = data["features"][0]["geometry"]["coordinates"][1]
        df.at[i, "Longitude"] = data["features"][0]["geometry"]["coordinates"][0]

        # Salva o progresso
        count += 1
        if count % 100 == 0:
            print(f"{count} registros processados")

        # A cada 1000 linhas, salva o CSV
        if count % 1000 == 0:
            df.to_csv(f"{name}.csv", index=False)

    except requests.exceptions.RequestException as e:
        print(f"Erro na solicitação para o endereço {search_text}: {e}")

# Salva o arquivo final
df.to_csv(f"{name}.csv", index=False)

100 registros processados
200 registros processados
300 registros processados
400 registros processados
500 registros processados
600 registros processados
700 registros processados
800 registros processados
900 registros processados
1000 registros processados
1100 registros processados

## Fast Food

In [16]:
import pandas as pd
import requests

# Carrega o arquivo Excel
df_full = pd.read_excel("PontosInteresse.xlsx", sheet_name=None)
name = "Fast Food"
df = df_full[name]

# Adiciona colunas para Latitude e Longitude, se não existirem
if "Latitude" not in df.columns:
    df["Latitude"] = None
if "Longitude" not in df.columns:
    df["Longitude"] = None

# Token e endpoint do Mapbox
token = "pk.eyJ1IjoicHJvamV0b2RhZG9zIiwiYSI6ImNtMXdiNjVobTBpa2Eya3BsMnR5OWxsd3AifQ.SGh5qTES1kmMN3VNFzZAwQ"
SAO_PAULO = (-46.63389, -23.55028)

# Loop para obter coordenadas de cada endereço
count = 0
for i, row in df.iterrows():
    search_text = f"{row['Endereço']} {row['Bairro']} São Paulo"
    url = f"https://api.mapbox.com/geocoding/v5/mapbox.places/{search_text}.json?access_token={token}&proximity={SAO_PAULO[0]},{SAO_PAULO[1]}"

    try:
        response = requests.get(url)
        data = response.json()

        # Verifica se há dados nas features
        if not data.get("features"):
            continue

        # Atualiza DataFrame com Latitude e Longitude
        df.at[i, "Latitude"] = data["features"][0]["geometry"]["coordinates"][1]
        df.at[i, "Longitude"] = data["features"][0]["geometry"]["coordinates"][0]

        # Salva o progresso
        count += 1
        if count % 100 == 0:
            print(f"{count} registros processados")

        # A cada 1000 linhas, salva o CSV
        if count % 1000 == 0:
            df.to_csv(f"{name}.csv", index=False)

    except requests.exceptions.RequestException as e:
        print(f"Erro na solicitação para o endereço {search_text}: {e}")

# Salva o arquivo final
df.to_csv(f"{name}.csv", index=False)

100 registros processados
200 registros processados
300 registros processados
400 registros processados
500 registros processados
600 registros processados
700 registros processados
800 registros processados
900 registros processados

## Hipermercados e Supermercados

In [18]:
import pandas as pd
import requests

# Carrega o arquivo Excel
df_full = pd.read_excel("PontosInteresse.xlsx", sheet_name=None)
name = "Hipermercados e Supermercados"
df = df_full[name]

# Adiciona colunas para Latitude e Longitude, se não existirem
if "Latitude" not in df.columns:
    df["Latitude"] = None
if "Longitude" not in df.columns:
    df["Longitude"] = None

# Token e endpoint do Mapbox
token = "pk.eyJ1IjoicHJvamV0b2RhZG9zIiwiYSI6ImNtMXdiNjVobTBpa2Eya3BsMnR5OWxsd3AifQ.SGh5qTES1kmMN3VNFzZAwQ"
SAO_PAULO = (-46.63389, -23.55028)

# Loop para obter coordenadas de cada endereço
count = 0
for i, row in df.iterrows():
    search_text = f"{row['Endereço']} {row['Bairro']} São Paulo"
    url = f"https://api.mapbox.com/geocoding/v5/mapbox.places/{search_text}.json?access_token={token}&proximity={SAO_PAULO[0]},{SAO_PAULO[1]}"

    try:
        response = requests.get(url)
        data = response.json()

        # Verifica se há dados nas features
        if not data.get("features"):
            continue

        # Atualiza DataFrame com Latitude e Longitude
        df.at[i, "Latitude"] = data["features"][0]["geometry"]["coordinates"][1]
        df.at[i, "Longitude"] = data["features"][0]["geometry"]["coordinates"][0]

        # Salva o progresso
        count += 1
        if count % 100 == 0:
            print(f"{count} registros processados")

        # A cada 1000 linhas, salva o CSV
        if count % 1000 == 0:
            df.to_csv(f"{name}.csv", index=False)

    except requests.exceptions.RequestException as e:
        print(f"Erro na solicitação para o endereço {search_text}: {e}")

# Salva o arquivo final
df.to_csv(f"{name}.csv", index=False)

100 registros processados
200 registros processados
300 registros processados
400 registros processados
500 registros processados
600 registros processados
700 registros processados
800 registros processados
900 registros processados
1000 registros processados

## Hortifruti

In [20]:
import pandas as pd
import requests

# Carrega o arquivo Excel
df_full = pd.read_excel("PontosInteresse.xlsx", sheet_name=None)
name = "Hortifruti"
df = df_full[name]

# Adiciona colunas para Latitude e Longitude, se não existirem
if "Latitude" not in df.columns:
    df["Latitude"] = None
if "Longitude" not in df.columns:
    df["Longitude"] = None

# Token e endpoint do Mapbox
token = "pk.eyJ1IjoicHJvamV0b2RhZG9zIiwiYSI6ImNtMXdiNjVobTBpa2Eya3BsMnR5OWxsd3AifQ.SGh5qTES1kmMN3VNFzZAwQ"
SAO_PAULO = (-46.63389, -23.55028)

# Loop para obter coordenadas de cada endereço
count = 0
for i, row in df.iterrows():
    search_text = f"{row['Endereço']} {row['Bairro']} São Paulo"
    url = f"https://api.mapbox.com/geocoding/v5/mapbox.places/{search_text}.json?access_token={token}&proximity={SAO_PAULO[0]},{SAO_PAULO[1]}"

    try:
        response = requests.get(url)
        data = response.json()

        # Verifica se há dados nas features
        if not data.get("features"):
            continue

        # Atualiza DataFrame com Latitude e Longitude
        df.at[i, "Latitude"] = data["features"][0]["geometry"]["coordinates"][1]
        df.at[i, "Longitude"] = data["features"][0]["geometry"]["coordinates"][0]

        # Salva o progresso
        count += 1
        if count % 100 == 0:
            print(f"{count} registros processados")

        # A cada 1000 linhas, salva o CSV
        if count % 1000 == 0:
            df.to_csv(f"{name}.csv", index=False)

    except requests.exceptions.RequestException as e:
        print(f"Erro na solicitação para o endereço {search_text}: {e}")

# Salva o arquivo final
df.to_csv(f"{name}.csv", index=False)


## Hospital

In [21]:
import pandas as pd
import requests

# Carrega o arquivo Excel
df_full = pd.read_excel("PontosInteresse.xlsx", sheet_name=None)
name = "Hospital"
df = df_full[name]

# Adiciona colunas para Latitude e Longitude, se não existirem
if "Latitude" not in df.columns:
    df["Latitude"] = None
if "Longitude" not in df.columns:
    df["Longitude"] = None

# Token e endpoint do Mapbox
token = "pk.eyJ1IjoicHJvamV0b2RhZG9zIiwiYSI6ImNtMXdiNjVobTBpa2Eya3BsMnR5OWxsd3AifQ.SGh5qTES1kmMN3VNFzZAwQ"
SAO_PAULO = (-46.63389, -23.55028)

# Loop para obter coordenadas de cada endereço
count = 0
for i, row in df.iterrows():
    search_text = f"{row['Endereço']} {row['Bairro']} São Paulo"
    url = f"https://api.mapbox.com/geocoding/v5/mapbox.places/{search_text}.json?access_token={token}&proximity={SAO_PAULO[0]},{SAO_PAULO[1]}"

    try:
        response = requests.get(url)
        data = response.json()

        # Verifica se há dados nas features
        if not data.get("features"):
            continue

        # Atualiza DataFrame com Latitude e Longitude
        df.at[i, "Latitude"] = data["features"][0]["geometry"]["coordinates"][1]
        df.at[i, "Longitude"] = data["features"][0]["geometry"]["coordinates"][0]

        # Salva o progresso
        count += 1
        if count % 100 == 0:
            print(f"{count} registros processados")

        # A cada 1000 linhas, salva o CSV
        if count % 1000 == 0:
            df.to_csv(f"{name}.csv", index=False)

    except requests.exceptions.RequestException as e:
        print(f"Erro na solicitação para o endereço {search_text}: {e}")

# Salva o arquivo final
df.to_csv(f"{name}.csv", index=False)

100 registros processados
200 registros processados
300 registros processados

## Petshop

In [22]:
import pandas as pd
import requests

# Carrega o arquivo Excel
df_full = pd.read_excel("PontosInteresse.xlsx", sheet_name=None)
name = "Petshop"
df = df_full[name]

# Adiciona colunas para Latitude e Longitude, se não existirem
if "Latitude" not in df.columns:
    df["Latitude"] = None
if "Longitude" not in df.columns:
    df["Longitude"] = None

# Token e endpoint do Mapbox
token = "pk.eyJ1IjoicHJvamV0b2RhZG9zIiwiYSI6ImNtMXdiNjVobTBpa2Eya3BsMnR5OWxsd3AifQ.SGh5qTES1kmMN3VNFzZAwQ"
SAO_PAULO = (-46.63389, -23.55028)

# Loop para obter coordenadas de cada endereço
count = 0
for i, row in df.iterrows():
    search_text = f"{row['Endereço']} {row['Bairro']} São Paulo"
    url = f"https://api.mapbox.com/geocoding/v5/mapbox.places/{search_text}.json?access_token={token}&proximity={SAO_PAULO[0]},{SAO_PAULO[1]}"

    try:
        response = requests.get(url)
        data = response.json()

        # Verifica se há dados nas features
        if not data.get("features"):
            continue

        # Atualiza DataFrame com Latitude e Longitude
        df.at[i, "Latitude"] = data["features"][0]["geometry"]["coordinates"][1]
        df.at[i, "Longitude"] = data["features"][0]["geometry"]["coordinates"][0]

        # Salva o progresso
        count += 1
        if count % 100 == 0:
            print(f"{count} registros processados")

        # A cada 1000 linhas, salva o CSV
        if count % 1000 == 0:
            df.to_csv(f"{name}.csv", index=False)

    except requests.exceptions.RequestException as e:
        print(f"Erro na solicitação para o endereço {search_text}: {e}")

# Salva o arquivo final
df.to_csv(f"{name}.csv", index=False)

100 registros processados

## Restaurante

In [24]:
import pandas as pd
import requests

# Carrega o arquivo Excel
df_full = pd.read_excel("PontosInteresse.xlsx", sheet_name=None)
name = "Restaurante"
df = df_full[name]

# Adiciona colunas para Latitude e Longitude, se não existirem
if "Latitude" not in df.columns:
    df["Latitude"] = None
if "Longitude" not in df.columns:
    df["Longitude"] = None

# Token e endpoint do Mapbox
token = "pk.eyJ1IjoicHJvamV0b2RhZG9zIiwiYSI6ImNtMXdiNjVobTBpa2Eya3BsMnR5OWxsd3AifQ.SGh5qTES1kmMN3VNFzZAwQ"
SAO_PAULO = (-46.63389, -23.55028)

# Loop para obter coordenadas de cada endereço
count = 0
for i, row in df.iterrows():
    search_text = f"{row['Endereço']} {row['Bairro']} São Paulo"
    url = f"https://api.mapbox.com/geocoding/v5/mapbox.places/{search_text}.json?access_token={token}&proximity={SAO_PAULO[0]},{SAO_PAULO[1]}"

    try:
        response = requests.get(url)
        data = response.json()

        # Verifica se há dados nas features
        if not data.get("features"):
            continue

        # Atualiza DataFrame com Latitude e Longitude
        df.at[i, "Latitude"] = data["features"][0]["geometry"]["coordinates"][1]
        df.at[i, "Longitude"] = data["features"][0]["geometry"]["coordinates"][0]

        # Salva o progresso
        count += 1
        if count % 100 == 0:
            print(f"{count} registros processados")

        # A cada 1000 linhas, salva o CSV
        if count % 1000 == 0:
            df.to_csv(f"{name}.csv", index=False)

    except requests.exceptions.RequestException as e:
        print(f"Erro na solicitação para o endereço {search_text}: {e}")

# Salva o arquivo final
df.to_csv(f"{name}.csv", index=False)

100 registros processados
200 registros processados

## Escola Privada

In [2]:
import pandas as pd
import requests

# Carrega o arquivo existente com dados parciais
name = "Escola Privada"
df = pd.read_csv(f"{name}.csv")

# Token e endpoint do Mapbox
token = "pk.eyJ1IjoicHJvamV0b2RhZG9zIiwiYSI6ImNtMXdiNjVobTBpa2Eya3BsMnR5OWxsd3AifQ.SGh5qTES1kmMN3VNFzZAwQ"
SAO_PAULO = (-46.63389, -23.55028)

# Loop para obter coordenadas de cada endereço apenas para as linhas que estão sem Latitude e Longitude
count = 0
for i, row in df.iterrows():
    # Verifica se a latitude e longitude já estão preenchidas
    if pd.notna(row['Latitude']) and pd.notna(row['Longitude']):
        continue  # Pula esta linha se as coordenadas já estão presentes

    # Monta o texto de busca e a URL para a API
    search_text = f"{row['Endereço']} {row['Bairro']} São Paulo"
    url = f"https://api.mapbox.com/geocoding/v5/mapbox.places/{search_text}.json?access_token={token}&proximity={SAO_PAULO[0]},{SAO_PAULO[1]}"

    try:
        # Faz a solicitação à API
        response = requests.get(url)
        data = response.json()

        # Verifica se há dados nas features
        if not data.get("features"):
            print(f"Nenhum resultado para o endereço: {search_text}")
            continue

        # Atualiza o DataFrame com a nova Latitude e Longitude
        df.at[i, "Latitude"] = data["features"][0]["geometry"]["coordinates"][1]
        df.at[i, "Longitude"] = data["features"][0]["geometry"]["coordinates"][0]

        # Incrementa o contador e exibe o progresso a cada 100 registros
        count += 1
        if count % 100 == 0:
            print(f"{count} registros processados")

        # Salva o progresso a cada 1000 linhas processadas
        if count % 1000 == 0:
            df.to_csv(f"{name}.csv", index=False)

    except requests.exceptions.RequestException as e:
        print(f"Erro na solicitação para o endereço {search_text}: {e}")

# Salva o arquivo final após processar todas as linhas
df.to_csv(f"{name}.csv", index=False)
print("Processo concluído e dados salvos em 'Escola Privada.csv'")

100 registros processados
200 registros processados
300 registros processados
400 registros processados
500 registros processados
600 registros processados
700 registros processados
800 registros processados
900 registros processados
1000 registros processados
1100 registros processados
1200 registros processados
1300 registros processados
1400 registros processados
Processo concluído e dados salvos em 'Escola Privada.csv'